project_name: alfred-azure-shortcuts
version: 2

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - id: resources
    binary: resources
    main: ./cmd/resources/resources.go
    ldflags:
      - -s -w
    goos:
      - darwin
    goarch:
      - arm64
  - id: resource_groups
    binary: resource_groups
    main: ./cmd/resource_groups/resource_groups.go
    ldflags:
      - -s -w
    goos:
      - darwin
    goarch:
      - arm64
  - id: subscriptions
    binary: subscriptions
    main: ./cmd/subscriptions/subscriptions.go
    ldflags:
      - -s -w
    goos:
      - darwin
    goarch:
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}.alfredworkflow"
    formats: ["zip"]
    files:
      - info.plist
      - icon.png
      - bin/**
      - images/**

snapshot:
  name_template: "{{.Commit}}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: trietsch
    name: alfred-azure-shortcuts
